name: twodtestgameproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.38.2
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.5.5
  flutter_joystick: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/characters/free_knight/
    - assets/images/characters/dude_monster/
    - assets/images/characters/owlet_monster/
    - assets/images/characters/pink_monster/
    - assets/images/enemies/slime3/
    - assets/images/enemies/undead_boss/
    - assets/images/environment/
    - assets/images/action/
    - assets/images/ui/
    - assets/images/ui/inventory/
    - assets/images/background/
    - assets/item/
    - assets/item/64x64/
    - assets/images/background/forest_map2.png
    - assets/images/scull.png
